# Generated by Django 5.2.4 on 2025-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientemail",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="clientemail",
            constraint=models.UniqueConstraint(
                fields=("client", "email"), name="unique_email_per_client"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientphonenumber",
            constraint=models.UniqueConstraint(
                fields=("client", "phone_number"), name="unique_phone_number_per_client"
            ),
        ),
    ]
